name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: CD Build Android
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install --frozen-lockfile
          cd ./android
          ./gradlew clean
          ./gradlew assembleRelease --warning-mode=all
      - uses: actions/upload-artifact@master
        with:
          name: apk
          path: ./android/app/build/outputs/apk/release/app-release.apk


  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y-%H-%M')"

      - name: Copy repository
        uses: actions/checkout@v2
      - run: mkdir -p /tmp/sonar/
      - run: curl --location --request POST 'https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2021.1-Cartografia-social-front&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500' > /tmp/sonar/fga-eps-mds-2021_1-Cartografia-social-front-${{ steps.date.outputs.date }}.json
      - uses: actions/upload-artifact@v2
        with:
          name: fga-eps-mds-2021_1-Cartografia-social-front-${{ steps.date.outputs.date }}.json
          path: /tmp/sonar/fga-eps-mds-2021_1-Cartografia-social-front-${{ steps.date.outputs.date }}.json
      - uses: actions/checkout@v2
      - name: Downlaod APK File
        uses: actions/download-artifact@master
        with:
          name: apk
          path: ./
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *.apk
            LICENSE
            /tmp/sonar/fga-eps-mds-2021_1-Cartografia-social-front-${{ steps.date.outputs.date }}.json
